name: black_formatter
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install black
      - run: black --check .
      - name: If needed, commit black changes to a new pull request
        if: failure()
        run: |
          black .
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'          
          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "fixup! Format Python code with psf/black push"
          git push  # --force origin HEAD:$GITHUB_REF